default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  database: eighteenman_with_pg_development

test:
  <<: *default
  database: eighteenman_with_pg_test

production:
  <<: *default
  database: eighteenman_with_pg_production
  username: eighteenman_with_pg
  password: <%= ENV['eighteenman_WITH_PG_DATABASE_PASSWORD'] %>